version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
    ports:
      - 8081:80
    networks:
      - webnet
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8082:80
    environment:
      - PMA_HOST=cubetechsoltera_mysql_1
      - PMA_USER=root
      - PMA_PASSWORD=test
    networks:
      - webnet
  mysql:
    image: mysql:5.6
    volumes:
       - mysqlData:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=cervezas_SISTEMA
      - MYSQL_USER=cervezas_ADMIN
      - MYSQL_PASSWORD=aA2oeC=dhTAI
    networks:
      - webnet
volumes:
  mysqlData:
networks:
  webnet:
